name: publish-vite-plugin

on:
  push:
    tags:
      - vite-plugin-**

jobs:
  publish:
    needs: [check]
    environment: production
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/setup@v2
      - run: pn --filter @styledeck/transform install
      - run: pn --filter @styledeck/transform run build
      - run: pn --filter @styledeck/vite-plugin install
      - run: pn stage publish --no-git-checks

  check:
    uses: ./.github/workflows/check.yml
    with:
      filter: '@styledeck/vite-plugin'
